version: '3'

tasks:
  default:
    - task: build
    - task: run

  run:
    cmds:
      - ./build/server.exe
      - ./build/agent.exe

  build:
    cmds:
      - powershell New-Item -ItemType Directory -Force -Path ./build

      - go build -o build/agent.exe ./cmd/agent
      - go build -o build/server.exe ./cmd/server

  test:
    cmds:
      - go test -v ./...