version: '3'

tasks:
  default:
    - task: buildForTest
    - task: test
    - task: iter1
    - task: iter2
    - task: iter3
    - task: iter4
    - task: iter5
    - task: iter6
    - task: iter7
    - task: iter8
    - task: iter9
    - task: iter10
    - task: iter11
    - task: iter12
    - task: iter13
    - task: iter14

  runServer:
    cmds:
      - go build -o build/server.exe ./cmd/server
      - ./build/server.exe

  runAgent:
    cmds:
      - go build -o build/agent.exe ./cmd/agent
      - ./build/agent.exe

  build:
    cmds:
      - powershell New-Item -ItemType Directory -Force -Path ./build
      - go build -o build/agent.exe ./cmd/agent -ldflags  -ldflags="-X main.buildVersion=v0.0.1 -X main.buildDate=$(shell date -u +%Y-%m-%dT%H:%M:%S) -X main.buildCommit=$(shell git rev-parse HEAD)"
      - go build -o build/server.exe ./cmd/server -ldflags  -ldflags="-X main.buildVersion=v0.0.1 -X main.buildDate=$(shell date -u +%Y-%m-%dT%H:%M:%S) -X main.buildCommit=$(shell git rev-parse HEAD)"

  buildForTest:
    cmds:
      - go build -o ./cmd/agent/agent.exe ./cmd/agent
      - go build -o ./cmd/server/server.exe ./cmd/server

  test:
    cmds:
      - go test -v ./...

  iter1:
    cmds:
     - ./metricstest.exe -test.v -test.run=^TestIteration1$$ -binary-path=./cmd/server/server.exe

  iter2:
    cmds:
      - ./metricstest.exe -test.v -test.run=^TestIteration2[AB]*$ -source-path=. -agent-binary-path=cmd/agent/agent.exe

  iter3:
    cmds:
      - ./metricstest.exe -test.v -test.run=^TestIteration3[AB]*$ -source-path=. -binary-path=./cmd/server/server.exe -agent-binary-path=./cmd/agent/agent.exe

  iter4:
    cmds:
      - ./metricstest -test.v -test.run=^TestIteration4$  -agent-binary-path=./cmd/agent/agent.exe -binary-path=./cmd/server/server.exe -server-port=8080 -source-path=.

  iter5:
    cmds:
      - ./metricstest -test.v -test.run=^TestIteration5$ -agent-binary-path=./cmd/agent/agent.exe -binary-path=./cmd/server/server.exe -server-port=8080 -source-path=.

  iter6:
    cmds:
      - ./metricstest -test.v -test.run=^TestIteration6$ -agent-binary-path=./cmd/agent/agent.exe -binary-path=./cmd/server/server.exe -server-port=8080 -source-path=.

  iter7:
    cmds:
      - ./metricstest -test.v -test.run=^TestIteration7$ -agent-binary-path=./cmd/agent/agent.exe -binary-path=./cmd/server/server.exe -server-port=8080 -source-path=.

  iter8:
    cmds:
      - metricstest -test.v -test.run=^TestIteration8$ -agent-binary-path=./cmd/agent/agent.exe -binary-path=./cmd/server/server.exe -server-port=8080 -source-path=.

  iter9:
    cmds:
      - metricstest -test.v -test.run=^TestIteration9$ -agent-binary-path=./cmd/agent/agent.exe -binary-path=./cmd/server/server.exe -file-storage-path=./tmp.txt -server-port=8080 -source-path=.

  iter10:
    cmds:
      - ./metricstest -test.v -test.run=^TestIteration10[AB]$ -agent-binary-path=./cmd/agent/agent.exe -binary-path=./cmd/server/server.exe -database-dsn='postgres://postgres:postgres@localhost:5432/metric-collector?sslmode=disable' -server-port=8080 -source-path=.

  iter11:
    cmds:
      - ./metricstest -test.v -test.run=^TestIteration11$ -agent-binary-path=./cmd/agent/agent.exe -binary-path=./cmd/server/server.exe -database-dsn=postgres://postgres:postgres@localhost:5432/metric-collector?sslmode=disable -server-port=8080 -source-path=.

  iter12:
    cmds:
      - ./metricstest -test.v -test.run=^TestIteration12$ -agent-binary-path=./cmd/agent/agent.exe -binary-path=./cmd/server/server.exe -database-dsn='postgres://postgres:postgres@localhost:5432/metric-collector?sslmode=disable' -server-port=8080 -source-path=.

  iter13:
    cmds:
      - ./metricstest -test.v -test.run=^TestIteration13$  -agent-binary-path=./cmd/agent/agent.exe  -binary-path=./cmd/server/server.exe  -database-dsn='postgres://postgres:postgres@localhost:5432/metric-collector?sslmode=disable'  -server-port=8080  -source-path=.

  iter14:
    cmds:
      - ./metricstest -test.v -test.run=^TestIteration14$  -agent-binary-path=./cmd/agent/agent.exe  -binary-path=./cmd/server/server.exe  -database-dsn='postgres://postgres:postgres@localhost:5432/metric-collector?sslmode=disable'  -key="SUPAHASH"  -server-port=8080  -source-path=.